<header role="banner" id="top">
	<h1><a href="/" target="_blank"><img src="/symbol/hp/baseball/games/2013/city/img/common/ci.gif" width="148" height="46" alt="NTT西日本"></a></h1>
	<ul id="topnavi">
		<li><a href="/" target="_blank">NTT西日本公式トップ</a></li>
		<li><a href="/share/aboutsite.html" target="_blank">このサイトについて</a></li>
		<li><a href="/share/privacy.html" target="_blank">プライバシーポリシー</a></li>
	</ul>
</header>
<nav id="global" role="navigation">
	<h2><a href="/symbol/hp/baseball/games/2016/city/index.html"><img src="img/common/logo.png" alt="第87回都市対抗野球大会"></a></h2>
	<ul>
		<li><a href="#main"><span class="fa fa-chevron-circle-down"></span>メインメニュー<i>Main menu</i></a></li>
		<li><a href="#topics"><span class="fa fa-chevron-circle-down"></span>トピックス <i>Topics</i></a></li>
		<li><a href="#link"><span class="fa fa-chevron-circle-down"></span>関連ページ <i>External link</i></a></li>
	</ul>
	<ul id="main">
		<li><a href="/symbol/hp/baseball/games/2016/city/index.html"><span class="fa fa-home"></span>トップページ<i>Top Page</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/tournament.html"><span class="fa fa-sitemap"></span>トーナメント表<i>Tournament Bracket</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/results.html"><span class="fa fa-list-ol"></span>試合結果<i>Results</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/gallery.html"><span class="fa fa-camera"></span>ギャラリー<i>Photo gallery</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/aid.html"><span class="fa fa-volume-up"></span>応援ガイド<i>Guidance of aid</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/access.html"><span class="fa fa-map-marker"></span>アクセスガイド<i>Guidance to a stadium</i> </a> </li>
	</ul>
	<ul id="topics">
		<li><a href="/symbol/hp/baseball/games/2016/city/addition.html"><span class="fa fa-plus"></span>補強選手 2016<i>Additional Player</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/mascot.html"><span class="fa fa-pencil-square-o"></span>マスコットの会場リポート<i>The mascot's game report</i></a></li>
		<!--<li><a href="/symbol/hp/baseball/games/2016/city/hero.html"><span class="fa fa-microphone"></span>ヒーローインタビュー<i>Hero Interview</i></a></li>-->
		<li><a href="/symbol/hp/baseball/games/2016/city/history.html"><span class="fa fa-trophy"></span>都市対抗野球とNTTグループの歴史<i>History</i></a></li>
		<li><a href="/symbol/hp/baseball/games/2016/city/past.html"><span class="fa fa-book"></span>NTT西日本 過去の戦績<i>The past results</i></a></li>
	</ul>
	<ul id="link">
		<li><a href="http://symbol.ntt-west.co.jp/nw/baseball/pitcher.php" target="_blank"><span class="fa fa-users"></span>NTT西日本硬式野球部 選手紹介</a></li>
	<li><a href="https://symbol.ntt-west.co.jp/nw/sendmessage.php?tid=baseball" target="_blank"><span class="fa fa-comments"></span>応援メッセージを送る</a></li>
	<li><a href="http://www.ntt-west.co.jp/symbol/mobile_mail/index.html" target="_blank" class="banner"><span class="fa fa-envelope-o"></span>速報メールマガジン ご登録</a></li>
	<li><a href="http://www.ntt-west.co.jp/symbol/fan/index.html" target="_blank" class="banner"><span class="fa fa-user-plus"></span>ファンクラブ ご登録</a></li>
	</ul>
	<p id="live"><a href="/symbol/hp/baseball/games/2016/city/scoreboard.php" ><img src="/symbol/hp/baseball/games/2016/city/img/common/live.png" alt="試合速報配信中！"></a></p>
</nav>